name: Deploy web to VPS

on:
  push:
    tags:
      - "v*"

concurrency:
  group: "deploy-web"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Build web
        working-directory: web
        run: npm ci && npm run build

      - name: Upload web files
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 2222
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: ${{ secrets.VPS_HOST_KEY }}
          source: web/dist/
          target: /var/www/edwinboon.dev/
